TODO #6
Then-We-Win/tww-app pull request #126
Opened 2020-12-13 04:28 UTC by chopcoding

This task is to create the page (container of components) for To-do. It should contain the following components:

```
<todo-header>
<todo-create-button>
<todo-toc>
<todo-list>
<todo-search>
<todo-task>
<todo-new>
<todo-edit>
<todo-user-list>
<todo-comment-history>
<todo-comment>
```

2020-12-15 15:45 UTC, onexdata requested changes
You've set up root listeners and events. This will conflict with the rest of the application.

Please review the "props down, events up" pattern of app building to get a better understanding on how components should be built and how there events should work.

Please see this article for an overview...
https://medium.com/quick-code/vue-communication-patterns-an-intro-to-props-down-and-events-up-pattern-d53340d2c94

2020-12-15 15:45 UTC, onexdata commented on front/src/components/todo/todo-create-button.vue
> +      this.$root.$emit('CREATE NEW')
Why are you emitting on $root?

2020-12-15 15:45 UTC, onexdata commented on front/src/layouts/Todo.vue
> +  created(){
Setting up root listeners is less than ideal.  Instead, on each component, you can create @eventName listeners.

Also, adding spaces to event names is a bad idea.

Also, not using scoped events will certainly cause conflicts in apps.  For example, a root event for a todo page called "create new" will certainly conflict with "create new" in any other page where you would create something new, as there is no indication that this belongs to the todo page.  Something like "todo.create" would be much more sustainable. However, emmiting on the root bus should always be avoided unless you need to, and in this case you don't even need to.

2020-12-15 18:18 UTC, chopcoding commented
Hi,
Thanks for the feedback, I will make those changes ASAP

2020-12-16 07:18 UTC, chopcoding commented
@onexdata 

I have made the necessary changes

2021-01-13 00:41 UTC, merged